version: "3.9"
services:
  dbt:
    build: .
    image: my-dbt-athena:latest
    container_name: dbt-athena
    working_dir: /usr/app
    volumes:
      - ../dbt-iceberg:/usr/app/dbt-iceberg
      - ../test_transactions.csv:/usr/app/test_transactions.csv
    tty: true
    stdin_open: true
